language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - ruby-head
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
